---
name: "CI"

on:
  push:
  schedule:
    - cron: '5 4 * * 1'

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} (${{ matrix.tox-envs }})"
    runs-on: "ubuntu-latest"
    env:
      PY_COLORS: 1

    strategy:
      matrix:
        include:
          - python-version: "3.7"
            tox-envs: "py37,py37-client,py37-server"
          - python-version: "3.11"
            tox-envs: "py311,py311-client,py311-server"
          - python-version: "pypy-3.7"
            tox-envs: "pypy3,pypy3-client,pypy3-server"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox

      - name: "Run tox targets for ${{ matrix.python-version }} (${{ matrix.tox-envs }})"
        continue-on-error: "${{ matrix.python-version == 'pypy-3.7' }}"
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          python -m tox -v -e ${{ matrix.tox-envs }} -- -v --color=yes
